server:
  port: 8081

spring:
  kafka:
    groupId: $Default
    topic-client-consumer: client-consumer
    bootstrap:
      servers: "localhost:9092"
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: $Default
      properties:
        spring:
          json:
            trusted:
              packages: com.kafka.consumer.domain